<a href="https://colab.research.google.com/github/sowjanyasirigadde/TASK_AIML/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
arr1 = ([1,2,3,4])
print(arr1)
arr2 = ([1,2,3,4],[5,6,7,8])
print(arr2)

ar = np.array([1,2,3])
print(ar)

print(ar)


zero = np.zeros((2,3))
print('zero array : ',zero)

one = np.ones((3,3))
print('ones array : ',one)

identity = np.eye(4,4)
print(identity)

ls = np.linspace(1,3,5)
print(ls)

randnum = ((np.random.rand(2,3))*10).astype(int)
print(randnum)

#dimentions of arr2
ashp = np.shape(arr2)
print(ashp)

arr = np.arange(2,10).reshape(4,2)
print(arr)

[1, 2, 3, 4]
([1, 2, 3, 4], [5, 6, 7, 8])
[1 2 3]
[1 2 3]
zero array :  [[0. 0. 0.]
 [0. 0. 0.]]
ones array :  [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[1.  1.5 2.  2.5 3. ]
[[2 1 2]
 [4 0 8]]
(2, 4)
[[2 3]
 [4 5]
 [6 7]
 [8 9]]


In [3]:
array1 = ([1,2,3,4],[5,6,7,8])
array2 = ([4,6,8,3],[2,5,7,9])
addition = np.sum(array2)
print(addition)

Mean = np.mean(array1)
print(Mean)

standard = np.std(array1)
print(standard)

Min = np.min(array1)
print(Min)
Max = np.max(array1)
print(Max)

ArgMin = np.argmin(array1)
print(ArgMin)

ArgMax = np.argmax(array1)
print(ArgMax)

X = np.array(([3,4],[5,6]))
Y = np.array(([8,9],[6,7]))
Dot = np.dot(X,Y)
print(Dot)

mat = np.arange(2,10).reshape(2,4)
print(mat)
print(mat.T)

sorts = np.sort(array2)
print(sorts)

44
4.5
2.29128784747792
1
8
0
7
[[48 55]
 [76 87]]
[[2 3 4 5]
 [6 7 8 9]]
[[2 6]
 [3 7]
 [4 8]
 [5 9]]
[[3 4 6 8]
 [2 5 7 9]]


In [4]:
# Importing NumPy
import numpy as np

# Creating Arrays
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([[1, 2, 3], [4, 5, 6],[9,10,11],[11,12,13]])

print("1D Array:", arr1)
print("2D Array:\n", arr2)

# Array with specific values
zeros = np.zeros((3,4))
ones = np.ones((2,3))
identity = np.eye(5)

print("Zeros:\n", zeros)
print("Ones:\n", ones)
print("Identity Matrix:\n", identity)

# Range and linspace
arange_arr = np.arange(1, 45, 2)
linspace_arr = np.linspace(1, 2, 4)

print("Arange:", arange_arr)
print("Linspace:", linspace_arr)

# Random numbers
rand_arr = np.random.rand(2,3)
print("Random Array:\n", rand_arr)
otp =( (rand_arr*1000000)).astype(int)
print("Random Array:\n", otp)

1D Array: [1 2 3 4 5 6]
2D Array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 9 10 11]
 [11 12 13]]
Zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Arange: [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43]
Linspace: [1.         1.33333333 1.66666667 2.        ]
Random Array:
 [[0.58618846 0.09220173 0.92615347]
 [0.03274278 0.08078504 0.68606318]]
Random Array:
 [[586188  92201 926153]
 [ 32742  80785 686063]]


In [5]:
# Example 1: Reshape and Transpose
matrix = np.arange(1, 13).reshape(4,3)
print("Matrix:\n", matrix)
print("Transpose:\n", matrix.T)

# Example 2: Mathematical operations
arr = np.array([10, 20, 30, 40])
print("Original Array:", arr)
print("Array + 5:", arr - 5)
print("Array squared:", arr ** 2)

# Example 3: Aggregate Functions
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Standard Deviation:", np.std(arr))

# Example 4: Matrix multiplication
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print("Matrix Multiplication:\n", np.dot(A,B))

# Example 5: Sorting
unsorted = np.array([3,1,4,1,5,9])
print("Sorted Array:", np.sort(unsorted))

Matrix:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Transpose:
 [[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
Original Array: [10 20 30 40]
Array + 5: [ 5 15 25 35]
Array squared: [ 100  400  900 1600]
Sum: 100
Mean: 25.0
Standard Deviation: 11.180339887498949
Matrix Multiplication:
 [[19 22]
 [43 50]]
Sorted Array: [1 1 3 4 5 9]


In [9]:
marks=np.array([65, 78, 90, 55, 88])
avg=np.mean(marks)
lowest=np.min(marks)
highest=np.max(marks)
print("Marks:",marks)
print("average marks:",avg)
print("lowest marks:",lowest)
print("highest marks:",highest)

Marks: [65 78 90 55 88]
average marks: 75.2
lowest marks: 55
highest marks: 90
